---
# tasks file for docker

- name: Add Ubuntu key server
  apt_key:
    keyserver: "{{ ubuntu_keyserver }}"
    id: "{{ ubuntu_keyserver_key }}"
    state: present
    validate_certs: no
  tags: docker  

- name: Add Docker Ubuntu PPA
  apt_repository:
    repo: "{{ ubuntu_docker_repo }}"
    state: present
  tags: docker

- name: Install Docker LXC & Apt Transport HTTP
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - lxc-docker
    - apt-transport-https
  tags: docker

- name: Create Docker symlink
  file: src=/usr/bin/{{ docker_command }} dest=/usr/local/bin/docker state=link force=yes
  tags: docker

- name: Add autocomplete
  command: sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/{{ docker_command }}
  tags: docker

- name: Expose Docker remote api
  lineinfile: dest=/etc/default/{{ docker_command }} line='DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock"' state=present
  notify: restart docker
  tags: docker